### ISSUE TITLE
AssertionError: [current_pairs] Violation of Primary Key Constraint

### ISSUE THREAD

**Issue by nikhil-pillai** [DataStories-UniPi/VCRA#2]
When running the 4-ecountering vessels file with the norway data I came across this error. The data set seems to be fine. Can you provide some insights into this please. Thanks in advance.

**Comment by nikhil-pillai** [comment]
<img width="463" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/cbbdfea3-edfb-4ee6-b0e1-e7e3bbb12570">

**Comment by andretri** [comment]
This behaviour indicates that there are duplicate records, i.e., the same vessel transmitted two or more AIS messages at the same time. Because the ```encountering_vessels``` method requires a stable sampling rate in your dataset, I would recommend removing all duplicate records and also temporally aligning vessel locations. 

Please see the cited paper for the complete preprocessing workflow.

**Comment by nikhil-pillai** [comment]
Are there any repo from your side regarding the preprocessing ? Interpolation and manipulating huge amount of data requires high level of processing and time. Kindly let me know if there are any. Thanks for this wonderful paper.

**Comment by andretri** [comment]
All methods for reproducing the preprocessing workflow of the paper can be found in the ```st_toolkit.py``` file (https://github.com/DataStories-UniPi/VCRA/blob/main/st_toolkit.py). To remove duplicate AIS messages, use the '''drop_duplicates''' method (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html) with ```subset = [<object_id_column_name>, <timestamp_column_name>]```

**Comment by nikhil-pillai** [comment]
I have the following error:
<img width="413" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/8a36ff35-f83f-4ac5-8ef9-f22e883d3300">

 from this dataset
 
<img width="754" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/e5b5ac65-e4ff-4fb5-ae3b-ca3ef0bc8456">

What could be the problem ? Tried resetting the index.

**Comment by andretri** [comment]
The o_id parameter should be a list, try ```geohl.add_speed(gif, o_id=['mmsi',], ...)```

**Comment by nikhil-pillai** [comment]
Yes. I changed the toolkit function to accept and convert as a list. I have tested out most of the functions with my normal data. I have a few final questions.
1) Can the df which I posted above be passed into functions such as classify_area_proximity, segment_trajectory, spatial_segmentation, temporal_segmentation or are there any new df that should be created for these.

2) The temporal_resampling_v2 takes in a df of nearly 10k rows with 50 different MMSI and returns only the resamples first MMSI value and returns 50 rows. The getattr seems to be the problem with my dataset. How can I eliminate these problems. Thankd for the detailed answers.

**Comment by andretri** [comment]
The ```temporal_segmentation``` method can be used directly with the DataFrame you posted earlier. 

For spatial segmentation, you'll need to run the ```classify_area_proximity``` before ```spatial_segmentation```. The former method requires an additional DataFrame for the areas of interest (i.e., ports) a list of which can be found within the files "[C1] * Port Index.zip" (c.f., https://zenodo.org/records/1167595).

**Comment by andretri** [comment]
For the issue related to ```temporal_resampling_v2```, please check the DataFrame you give as input. I would suggest to use a single vessel (for easier debugging) and make sure that the DataFrame is sorted w.r.t time. If the issue persists, please send me a couple of screenshots so that I can look into it further.

**Comment by nikhil-pillai** [comment]
Thank you for your response. Here if you can see there is a vessel with MMSI number 212979000 at 17:26 before resampling
<img width="436" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/a2ee4f8f-f940-478e-b2e7-483c7ac7b01e">

After resampling in the df you can see that only the first mmsi has values across the rows and other mmsi are not there
<img width="379" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/d298d200-92b8-4eb2-9c25-a3e032e8db95">

**Comment by andretri** [comment]
It seems like you give the entire DataFrame as input to the ```temporal_resampling_v2``` method. This method must be applied separately for each MMSI and/or trajectory id (in case you performed any segmentation task(s); e.g., ```groupby(['mmsi', 'traj_nr').apply(temporal_resampling_v2)```), and each group must be sorted w.r.t time - this can be achieved if you sort the data frame prior to resampling.

**Comment by nikhil-pillai** [comment]
Thank you very much. I finally figured out the logic. I did the groupby and passed the column in timeseconds but the return datetime is in the old unix UTC.

<img width="596" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/47f0c38d-6a9f-4472-9c44-08cdf10e6ebc">

Sorry for the multiple questions but this is my first time with temporal data processing. Thank you a bunch

**Comment by nikhil-pillai** [comment]
<img width="623" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/5b21f9d0-825c-4198-aa37-dbc59c4d3376">
Can this df used to extract encounters or should each MMSI be processed and joined as a df and then used into the function encounters.encountering_vessels(group_df). 
Thanks in advance professor.

**Comment by andretri** [comment]
At a first glance, the DataFrame seems fine. However, static information about the vessels is missing (specifically, their length). After including it, you can use the code in '''4-encountering-vessels.ipynb''' to find encountering vessels.

P.S.: Reset the index of your DataFrame, according to the following command ```df.reset_index(drop=False)```. Make sure to save it in CSV format so that it can be properly parsed in the following step(s).

**Comment by nikhil-pillai** [comment]
<img width="751" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/ae36b337-a9b9-4921-81a2-32f3afc31954">

1) After this part of the code (a) where we segment AIS for trajectories I applied the function to resample the time.
2) I added all the static information of the ship as you have mentioned earlier (b).
3) When I try the reset_index part if fails and pops up the error which is in the image provided above. 


(a)
```
group_df = geohl.temporal_segmentation(data_copy_slice, 'ts', threshold=30 * 60, min_pts=10, output_name='traj_nr')
grouped_df = group_df.groupby(['mmsi','traj_nr']).apply(geohl.temporal_resampling_v2)
```
b)
<img width="724" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/052f900e-069c-400f-adfb-300ea2b9823f">

**Comment by andretri** [comment]
This is an easy fix. Simply remove the ```mmsi``` column (```df.drop(['mmsi'], axis=1)```) and the reset index will function properly.

**Comment by nikhil-pillai** [comment]
Yes Professor. Fixed it with a drop level snippet from my prev issues. 
Can I pass a favourable area to the AIS using the function **create_area_bounds** and pass the output to the **classify_area_proximity** function to extract the ecounters happeing in the desired areas passed into the first function. 
Your work is really impressive and fantastic. Have tried many encounter library for bachelor thesis but nothing mostly works off the paper. Thank you for your work.

**Comment by andretri** [comment]
Yes, it is possible to use these methods to focus on AIS activity within an area of interest. 

Keep in mind that the ```create_area_bounds``` method takes as input a collection (GeoDataFrame/GeoSeries) of point geometries (e.g., port locations) and outputs their corresponding buffer (i.e., circle) with radius ```area_radius```.

If your area is already a Polygon, you may skip this step and use the ```classify_area_proximity``` method to focus on vessel activity within the specified area(s) (```label == -1```).

**Comment by nikhil-pillai** [comment]
Does the encountering pairs have the geomtery of both the target as well as own geometry or just the own vessel geometry ? The output seems to have just the geometry of own vessels.

**Comment by andretri** [comment]
Indeed, the encountering pairs have the geometry (i.e., trace) of the own vessel. However, since the algorithm is symmetric, in the sense that it compares the CRI of the own vessel to the target vessel and vice versa, the result contains both geometries. 


If you are interested in combining encountering vessels' geometry, a simple ```groupby.apply``` query will do the trick

**Comment by nikhil-pillai** [comment]
<img width="596" alt="image" src="https://github.com/DataStories-UniPi/VCRA/assets/117358175/e07f4695-70bb-4260-be7e-288d51241baa">
My encountering pairs are these. I wanted to just plot these and verify whether these are actually near and CRI of each points in a column would be nice. I tried the groupby by

`df2 = result.groupby(['own_mmsi','target_mmsi','datetime']).apply(lambda x: x[['own_geometry', 'target_geometry']].values.flatten())`

**Comment by nikhil-pillai** [comment]
I have one final question as of now. THe encounters returning have a low number of points for example a pair of mmsi encounter has maybe 5 pairs. Can I use the 'min_pts' in 'temporal_segmentation' to increase the number of points extracted for each encounter.

**Comment by nikhil-pillai** [comment]
Thank you prof. I have this one doubt. What I am seeing from the result is that there are instances of single ship enocunters and a few points. Is there any approaches for multi ship encounter extraction like for eg: An own ship is having a very few data as encounters and does your approach support extraction of multiple ships at the time frame.

**Comment by mpvalente24** [comment]
Hi @nikhil-pillai !

Could you provide me with the code (both the preprocessing and the final part to find the pairs: encountering_pairs, results = encounters.encountering_vessels(gdf))), because although my code runs and i did the preprocessing explained on the paper , and i did use a dataset that I think is the same as the one used in the paper, my ‘results’ dataframe is always empty.

My email address is miguelbro24@gmail.com if you want to share something with me!
